% Neighborhood air pollution is negatively associated with neurocognitive maturation in early adolescence
% contact: Omid Kardan, email: omidk@med.umich.edu
% Uses the csv files generated by the compile_variables_ABCD_air_pollution_2025.R
% Runs the PM2.5 PLS analysis and Makes figure 3 in the results
% Additionally, makes figures 1 and 2 in the methods section

% Uses the PLS scripts from https://www.rotman-baycrest.on.ca/index.php?section=345
% Download plscmd and plsgui and place in Pls_folder

% Uses bluewhitered from Nathan Childress (2022). 
% (https://www.mathworks.com/matlabcentral/fileexchange/4058-bluewhitered),
% MATLAB Central File Exchange.

% Uses export_fig from https://github.com/altmany/export_fig

%%  %% Create matched control group for the high_O3 participants
clear all
T_0 = read_abcd_beh('~\df_filled_beh_Y0_more.csv');
T_2 =read_abcd_beh('~\df_filled_beh_Y2_more.csv');


load('~/with_2b_2024.mat')
s_table = readtable("~/df_filled_demog_withcog_Y0_more.csv");
sub_11868 = table(s_table.subid_x);
usable_subs0 = innerjoin(sub_11868(with_2b_2024,:),T_0,"LeftKeys","Var1","RightKeys","subids");
tfu = table(T_2.subids, T_2.NBK,  T_2.NIH5,  T_2.smri_thick_cdk_mean,'VariableNames',{'subids','NBK_y2' ,'NIH_y2' ,'thick_y2'});
usable_subs = innerjoin(usable_subs0,tfu,"LeftKeys","Var1","RightKeys","subids");
usable_subs.cog = nanmean([usable_subs.NBK usable_subs.NIH5./120],2) + nanmean([usable_subs.NBK_y2 usable_subs.NIH_y2./120],2);
usable_subs.neur = usable_subs.smri_thick_cdk_mean + usable_subs.thick_y2;


pm_high1 = find(usable_subs.reshist_addr1_pm252016aa>9 & ~isnan(usable_subs.cog) & ~isnan(usable_subs.neur) ...
    & usable_subs.reshist_addr1_o3_2016_max<70); % mean_year in ug/m3; US_EPA 9

% comment out the next 2 lines below until the low_o3 thresh is finalized 
load(['~/num_matches_subs_pm9_no2excluded.mat']);
pm_high =pm_high1(num_matches_subs_pm9_no2excluded >1); 


% pm_high = pm_high1;   %uncomment this line until the low_pm thresh is finalized
pm_high_n = length(pm_high);
pm_low = find(usable_subs.reshist_addr1_pm252016aa<7); % increment until matching is successful 

usable_subs.raceth = usable_subs.White;
usable_subs.raceth(usable_subs.Black == 1) = 2;
usable_subs.raceth(usable_subs.Hispanic == 1) = 3;
usable_subs.raceth(usable_subs.Asian == 1) = 4;
usable_subs.raceth(usable_subs.Other == 1) = 5;
usable_subs.interview_age(isnan(usable_subs.interview_age)) = nanmean(usable_subs.interview_age);
usable_subs.agey = round(usable_subs.interview_age/6);
usable_subs.HighestEd(isnan(usable_subs.HighestEd)) = nanmean(usable_subs.HighestEd);
usable_subs.edu = round(usable_subs.HighestEd/5);

income_matches = cell(pm_high_n,1);
age_matches = cell(pm_high_n,1);
sex_matches = cell(pm_high_n,1);
raceth_matches = cell(pm_high_n,1);
edu_matches = cell(pm_high_n,1);

for k =1:pm_high_n
    
    if ~isnan(usable_subs.Income(pm_high(k)) )
        a = find(round(usable_subs.Income) == round(usable_subs.Income(pm_high(k))));
    else a = pm_low;
    end
        income_matches{k} = intersect(pm_low,a);
        
    if ~isnan(usable_subs.agey(pm_high(k)))
        a = find(usable_subs.agey == usable_subs.agey(pm_high(k)));
    else a = pm_low;
    end
        age_matches{k} = intersect(pm_low,a);
    
    if ~isnan(usable_subs.Male_bin(pm_high(k)))
        a = find(usable_subs.Male_bin == usable_subs.Male_bin(pm_high(k)));
    else a = pm_low;
    end
         sex_matches{k} = intersect(pm_low,a);
         
    if ~isnan(usable_subs.raceth(pm_high(k)))
        a = find(usable_subs.raceth == usable_subs.raceth(pm_high(k)));
    else a = pm_low;
    end
         raceth_matches{k} = intersect(pm_low,a);
    
    if ~isnan(usable_subs.edu(pm_high(k)))
        a = find(usable_subs.edu == usable_subs.edu(pm_high(k)));
    else a = pm_low;
    end
         edu_matches{k} = intersect(pm_low,a);
            
end
cont_mj = cell(pm_high_n,1); cont_mj_full = cell(pm_high_n,1); cont_mj_bare = cell(pm_high_n,1);
for k = 1:pm_high_n
    gg = intersect( intersect(sex_matches{k},income_matches{k}), intersect(raceth_matches{k},edu_matches{k}));
    cont_mj_full{k} = setdiff(intersect( gg, age_matches{k}  ),  pm_high);
    cont_mj{k} = setdiff( gg,  pm_high);
    gg2 = intersect(income_matches{k}, raceth_matches{k});
    cont_mj_bare{k} = setdiff( intersect(gg2,edu_matches{k}),  pm_high);
    

end

% uncomment the next four lines until the low_o3 thresh is finalized
% num_matches_subs_pm9_no2excluded =[];
% for l=1:length(pm_high)
% num_matches_subs_pm9_no2excluded = [num_matches_subs_pm9_no2excluded; length(cont_mj_bare{l})];
% end

HCss = []; llls =[];
for ww = 1:10000
    HCs =NaN(pm_high_n,1);
    for k=1:pm_high_n
        if ~isempty(cont_mj_full{k})
            if length(cont_mj_full{k}) >1
                for jjk = 1: length(cont_mj_full{k})
                    dd = randperm(length(cont_mj_full{k}),1);
                    if ~ismember(cont_mj_full{k}(dd),HCs)
                        continue
                    end
                end
            else dd =1;
            end
            HCs(k) = cont_mj_full{k}(dd);
            
            
        elseif ~isempty(cont_mj{k})
            if length(cont_mj{k}) >1
                for jjk = 1: length(cont_mj{k})
                    dd = randperm(length(cont_mj{k}),1);
                    if ~ismember(cont_mj{k}(dd),HCs)
                        continue
                    end
                end
            else dd =1;
            end
            HCs(k) = cont_mj{k}(dd);
            
            
        elseif ~isempty(cont_mj_bare{k})
            if length(cont_mj_bare{k}) >1
                for jjk = 1: length(cont_mj_bare{k})
                    dd = randperm(length(cont_mj_bare{k}),1);
                    if ~ismember(cont_mj_bare{k}(dd),HCs)
                        continue
                    end
                end
            else dd =1;
            end
            HCs(k) = cont_mj_bare{k}(dd);
        end
    end
    llls = [llls; length(unique(HCs))];
        
        HCss = [HCss  HCs];

end

 matches = HCss(:,1);
for j=1:10000
    [v, w] = unique( matches, 'stable' );
    duplicate_indices = setdiff( 1:numel(matches), w );
    if length(duplicate_indices)==0
        break
    end
    matches(duplicate_indices) = HCss(duplicate_indices,j);
end
        
matches_for_highpm25 = unique(matches); 

% check if all Cohen's ds are smaller than .2; if not increase the pm_low threshold until that is achieved
T_ = usable_subs;
cohd = (nanmean(T_.age(pm_high))-nanmean(T_.age(setdiff(1:3645,pm_high))) )/ sqrt(nanvar(T_.age(pm_high))+nanvar(T_.age(setdiff(1:3645,pm_high))) )
cohd = (nanmean(T_.age(pm_high))-nanmean(T_.age(pm_low)) )/ sqrt(nanvar(T_.age(pm_high))+nanvar(T_.age(pm_low)) )
cohd = (nanmean(T_.age(pm_high))-nanmean(T_.age(matches_for_highpm25)) )/ sqrt(nanvar(T_.age(pm_high))+nanvar(T_.age(matches_for_highpm25)) )

cohd = (nanmean(T_.Income(pm_high))-nanmean(T_.Income(setdiff(1:3645,pm_high))) )/ sqrt(nanvar(T_0.Income(pm_high))+nanvar(T_.Income(setdiff(1:3645,pm_high))) )
cohd = (nanmean(T_.Income(pm_high))-nanmean(T_.Income(pm_low)) )/ sqrt(nanvar(T_.Income(pm_high))+nanvar(T_.Income(pm_low)) )
cohd = (nanmean(T_.Income(pm_high))-nanmean(T_.Income(matches_for_highpm25)) )/ sqrt(nanvar(T_.Income(pm_high))+nanvar(T_.Income(matches_for_highpm25)) )


cohd = (nanmean(T_.HighestEd(pm_high))-nanmean(T_.HighestEd(setdiff(1:3645,pm_high))) )/ sqrt(nanvar(T_.HighestEd(pm_high))+nanvar(T_.HighestEd(setdiff(1:3645,pm_high))) )
cohd = (nanmean(T_.HighestEd(pm_high))-nanmean(T_.HighestEd(pm_low)) )/ sqrt(nanvar(T_.HighestEd(pm_high))+nanvar(T_.HighestEd(pm_low)) )
cohd = (nanmean(T_.HighestEd(pm_high))-nanmean(T_.HighestEd(matches_for_highpm25)) )/ sqrt(nanvar(T_.HighestEd(pm_high))+nanvar(T_.HighestEd(matches_for_highpm25)) )

cohd = (nanmean(T_.Black(pm_high))-nanmean(T_.Black(setdiff(1:3645,pm_high))) )/ sqrt(nanvar(T_.Black(pm_high))+nanvar(T_.Black(setdiff(1:3645,pm_high))) )
cohd = (nanmean(T_.Black(pm_high))-nanmean(T_.Black(pm_low)) )/ sqrt(nanvar(T_.Black(pm_high))+nanvar(T_.Black(pm_low)) )
cohd = (nanmean(T_.Black(pm_high))-nanmean(T_.Black(matches_for_highpm25)) )/ sqrt(nanvar(T_.Black(pm_high))+nanvar(T_.Black(matches_for_highpm25)) )

cohd = (nanmean(T_.White(pm_high))-nanmean(T_.White(setdiff(1:3645,pm_high))) )/ sqrt(nanvar(T_.White(pm_high))+nanvar(T_.White(setdiff(1:3645,pm_high))) )
cohd = (nanmean(T_.White(pm_high))-nanmean(T_.White(pm_low)) )/ sqrt(nanvar(T_.White(pm_high))+nanvar(T_.White(pm_low)) )
cohd = (nanmean(T_.White(pm_high))-nanmean(T_.White(matches_for_highpm25)) )/ sqrt(nanvar(T_.White(pm_high))+nanvar(T_.White(matches_for_highpm25)) )

cohd = (nanmean(T_.Hispanic(pm_high))-nanmean(T_.Hispanic(setdiff(1:3645,pm_high))) )/ sqrt(nanvar(T_.Hispanic(pm_high))+nanvar(T_.Hispanic(setdiff(1:3645,pm_high))) )
cohd = (nanmean(T_.Hispanic(pm_high))-nanmean(T_.Hispanic(pm_low)) )/ sqrt(nanvar(T_.Hispanic(pm_high))+nanvar(T_.Hispanic(pm_low)) )
cohd = (nanmean(T_.Hispanic(pm_high))-nanmean(T_.Hispanic(matches_for_highpm25)) )/ sqrt(nanvar(T_.Hispanic(pm_high))+nanvar(T_.Hispanic(matches_for_highpm25)) )

% save the final match group and the high_o3 groups

matches_279 = unique(matches); % save these as your matched controls
pmhigh_348_o3excluded = pm_high; % save these as your high_pm group

%% Run PLS based on the high_pm25 and its matched low_pm25 control group

clear all
T_0 = read_abcd_beh('~\df_filled_beh_Y0_more.csv');
T_2 =read_abcd_beh('~\df_filled_beh_Y2_more.csv');


load('~/usable_subs.mat')
T_ = usable_subs;

load('pm_matches_279_o3excluded.mat')
load('pmhigh_348_o3excluded.mat')

addpath(genpath('~\Pls'));
rng('default');
groups{1} = [matches_279];
groups{2} = [pmhigh_348_o3excluded];
nTimes = 2;

datamat_lst = cell(length(groups),1); 
% ####*****************####
T_0.cog = nanmean([T_0.NBK T_0.NIH5./120],2);
T_2.cog = nanmean([T_2.NBK T_2.NIH5./120],2);


for g = 1:numel(groups)
    for c = 1:nTimes
        for s = 1:numel(groups{g})
            sub_id = char(T_.Var1(groups{g}(s)));
            
            vec2 =[];
            if c==1
                locb = find(T_0.subids == sub_id);
                if length(locb)==0
                    sub_id
                end
                vec2 = [T_0.mat_score(locb)   T_0.cog(locb)  T_0.smri_thick_cdk_mean(locb)];
                                                    
            end
            
            if c==2
                loct = find(T_2.subids == sub_id);
                if length(loct)==0
                    sub_id
                end
                vec2 = [T_2.mat_score(loct)  T_2.cog(loct)  T_2.smri_thick_cdk_mean(loct)];
                  

            end
            
            datamat_lst{g} = [datamat_lst{g}; vec2];
            s;
            
        end
    end
end

num_subj = [length(groups{1})  length(groups{2})];
num_cond = nTimes;
option.method = 1; %Task PLS1  or behavioral PLS3
option.num_boot = 1000;
option.num_perm = 1000;
option.meancentering_type=[2]; % 0 remove overall group diffrences,  1 remove overall condition diffrences
result = pls_analysis(datamat_lst, num_subj, num_cond, option);
result.datamat_lst = datamat_lst;
ps = result.perm_result.sprob
% save the 'result' variable as PLS_result_279lowpm_348hpm_y0_y2_o3excluded.mat

%% plotting the results
clear all
addpath(genpath('Z:\MatlabGraphics\bluewhitered'))

load('PLS_result_279lowpm_348hpm_y0_y2_o3excluded.mat');  pm = 'High PM2.5';

ps = result.perm_result.sprob
load('~/usable_subs.mat')
T_q = usable_subs;

T_0 = read_abcd_beh('~\df_filled_beh_Y0_more.csv');
T_2 =read_abcd_beh('~\df_filled_beh_Y2_more.csv');
tfu = table(T_2.subids, T_2.interview_age,T_2.nruns,'VariableNames',{'subids','age_Y2','nruns_Y2'});
T_ = innerjoin(T_q,tfu,"LeftKeys","Var1","RightKeys","subids");

load('pm_matches_279_o3excluded.mat')
load('pmhigh_348_o3excluded.mat')
matches = matches_279;
pmhigh = pmhigh_348_o3excluded;


Sites = zeros(3645,22);
for K=1:22
    Sites((T_.site_id_l == K),K) = 1;
end

lv=1;   %~##########

lg1 = length(matches); lg2 = length(pmhigh);
adjy0cont = zeros(2*(lg1+lg2),1);
adjy0cont(1:lg1) = 1;

adjy2cont = zeros(2*(lg1+lg2),1);
adjy2cont(lg1+1:2*lg1) = 1;

adjy0pm = zeros(2*(lg1+lg2),1);
adjy0pm(2*lg1+1:2*lg1+lg2) = 1;

adjy2pm = zeros(2*(lg1+lg2),1);
adjy2pm(2*lg1+lg2+1:2*(lg1+lg2)) = 1;


covariates_y0cont = [T_.pFD_y0(matches)   Sites(matches,:)  T_.White(matches) T_.Black(matches) T_.Hispanic(matches) T_.HighestEd(matches) T_.Income(matches) T_.Male_bin(matches)  T_.interview_age(matches)  T_.Ingenia(matches) T_.Achieva(matches) T_.Discovery(matches)  T_.Pfit(matches) T_.nruns(matches) T_.reshist_addr1_adi_wsum(matches) T_.PF10_lavaan(matches) T_.pds_ss(matches)];
covariates_y2cont = [T_.pFD_y2(matches)   Sites(matches,:)  T_.White(matches) T_.Black(matches) T_.Hispanic(matches) T_.HighestEd(matches) T_.Income(matches) T_.Male_bin(matches)  T_.age_Y2(matches)   T_.Ingenia(matches) T_.Achieva(matches) T_.Discovery(matches)  T_.Pfit(matches) T_.nruns_Y2(matches) T_.reshist_addr1_adi_wsum(matches) T_.PF10_lavaan(matches) T_.pds_ss(matches)];
covariates_y0pm = [T_.pFD_y0(pmhigh)   Sites(pmhigh,:)  T_.White(pmhigh) T_.Black(pmhigh) T_.Hispanic(pmhigh) T_.HighestEd(pmhigh) T_.Income(pmhigh) T_.Male_bin(pmhigh)  T_.interview_age(pmhigh)   T_.Ingenia(pmhigh) T_.Achieva(pmhigh) T_.Discovery(pmhigh)  T_.Pfit(pmhigh) T_.nruns(pmhigh) T_.reshist_addr1_adi_wsum(pmhigh) T_.PF10_lavaan(pmhigh) T_.pds_ss(pmhigh)];
covariates_y2pm = [T_.pFD_y2(pmhigh)   Sites(pmhigh,:)  T_.White(pmhigh) T_.Black(pmhigh) T_.Hispanic(pmhigh) T_.HighestEd(pmhigh) T_.Income(pmhigh) T_.Male_bin(pmhigh)  T_.age_Y2(pmhigh)  T_.Ingenia(pmhigh) T_.Achieva(pmhigh) T_.Discovery(pmhigh)  T_.Pfit(pmhigh) T_.nruns_Y2(pmhigh) T_.reshist_addr1_adi_wsum(pmhigh) T_.PF10_lavaan(pmhigh) T_.pds_ss(pmhigh)];


covariates = [covariates_y0cont; covariates_y2cont; covariates_y0pm; covariates_y2pm];

[a1 ] = partialcorr([result.usc(:,lv),adjy0cont],covariates, 'Rows', 'pairwise');
[a2 ] = partialcorr([result.usc(:,lv),adjy2cont], covariates, 'Rows', 'pairwise');
[a3 ] = partialcorr([result.usc(:,lv),adjy0pm], covariates, 'Rows', 'pairwise');
[a4 ] = partialcorr([result.usc(:,lv),adjy2pm], covariates, 'Rows', 'pairwise');

a1s =[]; a2s =[]; a3s =[]; a4s =[]; b1s=[];b2s=[];b3s=[];
dats = [result.datamat_lst{1, 1}; result.datamat_lst{2, 1}];

nboot = 5000;
for jj=1:nboot
   rand_inds1 = randi([1,lg1],lg1,1); rand_inds11 = randi([1,lg1],lg1,1); 
   rand_inds2 = randi([1,lg2],lg2,1); rand_inds22 = randi([1,lg2],lg2,1);
   inds = [rand_inds1; lg1+ rand_inds11; 2*lg1+ rand_inds2; 2*lg1+lg2+ rand_inds22];
   a11 = partialcorr([result.usc(inds,lv),adjy0cont(inds)], covariates(inds,:), 'Rows', 'pairwise');
   a1s = [a1s; a11(1,2)];
   a22 = partialcorr([result.usc(inds,lv),adjy2cont(inds)], covariates(inds,:), 'Rows', 'pairwise');
a2s = [a2s; a22(1,2)];
a33 = partialcorr([result.usc(inds,lv),adjy0pm(inds)], covariates(inds,:), 'Rows', 'pairwise');
a3s = [a3s; a33(1,2)];
a44 = partialcorr([result.usc(inds,lv),adjy2pm(inds)] , covariates(inds,:), 'Rows', 'pairwise');
a4s = [a4s; a44(1,2)];


   b11 = partialcorr([result.usc(inds,lv), dats(inds,1)], covariates(inds,:), 'Rows', 'pairwise');
   b1s = [b1s; b11(1,2)];
   b22 = partialcorr([result.usc(inds,lv),dats(inds,2)], covariates(inds,:), 'Rows', 'pairwise');
b2s = [b2s; b22(1,2)];
b33 = partialcorr([result.usc(inds,lv),dats(inds,3)], covariates(inds,:), 'Rows', 'pairwise');
b3s = [b3s; b33(1,2)];

end

 
 gt_contrast2 = (-1).*[a1s, a2s, a3s, a4s];
 gt_contrast2b = (-1).*[b1s, b2s, b3s];
 
p1 = 1 - length(find(  (gt_contrast2(:,2)-gt_contrast2(:,1)) > (mean(gt_contrast2(:,4)) - mean(gt_contrast2(:,3)) ) ) )/nboot
p2 = 1 - (length(find(  (gt_contrast2(:,4)>gt_contrast2(:,3))  ) )/nboot);
p3 = 1 - (length(find(  (gt_contrast2(:,2)>gt_contrast2(:,1))  ) )/nboot);
ef = mean(gt_contrast2(:,2))-mean(gt_contrast2(:,1))
 

 addpath(genpath('Z:\MatlabGraphics\export_fig-master'));
pmcol = [.87 .67 .31];
f1 = figure;
hold on
xss = [1,1.8,3.2,4];
sqlist = [1,2,3,4]; % order of grouping columns
for sq=1:4
if (sq==1 | sq==2); col = [.45 .65 0.75];  % color for columns 1 and 2 (HC)
else
    col = pmcol;
end
k = sqlist(sq);
   mm = mean(gt_contrast2(:,k));
  negs = mm - prctile(gt_contrast2(:,k),5);
   pos = prctile(gt_contrast2(:,k),95) - mm;
   bar(xss(sq),mean(gt_contrast2(:,k)),'FaceColor',col,'EdgeColor',col);
   errorbar(xss(sq),mean(gt_contrast2(:,k)),negs,pos,'.k');
end
set(gca,'XTick',xss,'XTickLabels',{'Baseline (9-10 y)','Follow-up (11-12 y)','Baseline (9-10 y)','Follow-up (11-12 y)'},...
    'XTickLabelRotation',45,'FontSize',22);
ylabel('PLS group-by-time loading (partial corr)'); ylim([-.2,.22]);
f1.Position = [100 100 500 900];
hold off
export_fig -m5 -transparent pm25_pls_lv1_gtbars_partial_o3excluded.jpg

f2 = figure;
hold on
for k=1:3
    col = [.74 .65 .63];
 mmb = mean(gt_contrast2b(:,k));
 
   negsb = mmb - prctile(gt_contrast2b(:,k),5);
   posb = prctile(gt_contrast2b(:,k),95) - mmb;
    bar(k*.8,mean(gt_contrast2b(:,k)),'FaceColor',col,'EdgeColor',col,'BarWidth',.45);
    errorbar(k*.8,mean(gt_contrast2b(:,k)),negsb,posb,'.k');
end
set(gca,'XTick',[.8,1.6,2.4],'XTickLabels',{'Cort FC maturation','Cog task perf','Cort GM thickness'},...
    'XTickLabelRotation',45,'FontSize',22);
ylabel('PLS neurocognitve loading (partial corr)'); ylim([-1,1]); %axis square
f2.Position = [100 100 500 900];
hold off  
export_fig -m5 -transparent pm25_pls_lv1_ncbars_partial_o3excluded.jpg
cbcovs = result.s.^2./sum(result.s.^2); % sigma_xy


%% example sub connectome arrangements (Figure 1)
% See Kardan et al., 2025 Dev. Cog. Neuro. for the Adult and Baby netwroks .mat files
% Read slightly shuffled connectome of Participant A
load('~\adult_net_arrange\NDARAAAAAA_baselineYear1Arm1_rest_1_adult.mat')
load('~\baby_net_arrange\NDARAAAAAA_baselineYear1Arm1_rest_1_baby.mat')

addpath(genpath('Z:\MatlabGraphics\bluewhitered')) % 
figure;
subplot(2,2,1)
load('GBnetworknames.mat')
baby_conn1 = baby_conn;
baby_conn1(tril(ones(333),-1)==0) = 0;
imagesc(baby_conn1,[-.55,1]);colormap(bluewhitered), colorbar;
xnames =networknames(1:11); 
netsizes1 = [0 50 48 26 26 18 17 28 54 28 33];
netsizes = [50 48 26 26 18 17 28 54 28 33 5];
set(gca,'XTick',round(cumsum(netsizes1)+ netsizes/2),'Xticklabel',xnames,...
         'XtickLabelRotation',45,'FontSize',13);
set(gca,'YTick',round(cumsum(netsizes1)+ netsizes/2),'Yticklabel',xnames,...
         'XtickLabelRotation',45,'FontSize',13);

makans = cumsum(netsizes);
for j=1:length(netsizes)
line([makans(j),makans(j)],[makans(j) ,333],'Color','black');
end
for j=1:length(netsizes)
line([0 ,makans(j)],[makans(j),makans(j)],'Color','black');
end
title('Participant A (baby networks)');
line([0 ,333],[0 ,333],'Color','black');
ylabel('average correlation value','Position',[381,167,1]); axis square


subplot(2,2,2)
adult_conn1 = adult_conn;
adult_conn1(tril(ones(333),-1)==0) = 0;
imagesc(adult_conn1,[-.55,1]);colormap(bluewhitered), colorbar;
load('GAnetnames.mat')
xnames = GAnetnames;
netsizes1 = [0 24    40     5    41    32    24    47     8    38     8     4    23];
netsizes = [24    40     5    41    32    24    47     8    38     8     4    23    39];
set(gca,'XTick',round(cumsum(netsizes1)+ netsizes/2),'Xticklabel',xnames,...
         'XtickLabelRotation',45,'FontSize',13);
set(gca,'YTick',round(cumsum(netsizes1)+ netsizes/2),'Yticklabel',xnames,...
         'XtickLabelRotation',45,'FontSize',13);

makans = cumsum(netsizes);
for j=1:length(netsizes)
line([makans(j),makans(j)],[makans(j) ,333],'Color','black');
end
for j=1:length(netsizes)
line([0 ,makans(j)],[makans(j),makans(j)],'Color','black');
end

title('Participant A (adult networks)');
line([0 ,333],[0 ,333],'Color','black');
ylabel('average correlation value','Position',[381,167,1]); axis square


% Read slightly shuffled connectome of Participant B
load('~\adult_net_arrange\NDARBBBBB_baselineYear1Arm1_rest_1_adult.mat')
load('~\baby_net_arrange\NDARBBBBB_baselineYear1Arm1_rest_1_baby.mat')

addpath(genpath('~\bluewhitered')) 

subplot(2,2,3)
load('GBnetworknames.mat')
baby_conn1 = baby_conn;
baby_conn1(tril(ones(333),-1)==0) = 0;
imagesc(baby_conn1,[-.55,1]);colormap(bluewhitered), colorbar;
xnames =networknames(1:11); 
netsizes1 = [0 50 48 26 26 18 17 28 54 28 33];
netsizes = [50 48 26 26 18 17 28 54 28 33 5];
set(gca,'XTick',round(cumsum(netsizes1)+ netsizes/2),'Xticklabel',xnames,...
         'XtickLabelRotation',45,'FontSize',13);
set(gca,'YTick',round(cumsum(netsizes1)+ netsizes/2),'Yticklabel',xnames,...
         'XtickLabelRotation',45,'FontSize',13);

makans = cumsum(netsizes);
for j=1:length(netsizes)
line([makans(j),makans(j)],[makans(j) ,333],'Color','black');
end
for j=1:length(netsizes)
line([0 ,makans(j)],[makans(j),makans(j)],'Color','black');
end
title('Participant B (baby networks)');
line([0 ,333],[0 ,333],'Color','black');
ylabel('average correlation value','Position',[381,167,1]); axis square


subplot(2,2,4)
adult_conn1 = adult_conn;
adult_conn1(tril(ones(333),-1)==0) = 0;
imagesc(adult_conn1,[-.55,1]);colormap(bluewhitered), colorbar;
load('GAnetnames.mat')
xnames = GAnetnames;
netsizes1 = [0 24    40     5    41    32    24    47     8    38     8     4    23];
netsizes = [24    40     5    41    32    24    47     8    38     8     4    23    39];
set(gca,'XTick',round(cumsum(netsizes1)+ netsizes/2),'Xticklabel',xnames,...
         'XtickLabelRotation',45,'FontSize',13);
set(gca,'YTick',round(cumsum(netsizes1)+ netsizes/2),'Yticklabel',xnames,...
         'XtickLabelRotation',45,'FontSize',13);

makans = cumsum(netsizes);
for j=1:length(netsizes)
line([makans(j),makans(j)],[makans(j) ,333],'Color','black');
end
for j=1:length(netsizes)
line([0 ,makans(j)],[makans(j),makans(j)],'Color','black');
end

title('Participant B (adult networks)');
line([0 ,333],[0 ,333],'Color','black');
ylabel('average correlation value','Position',[381,167,1]); axis square

%
%% Figure 2 plots of AFC, cog perf, and cort thickness at Y0 and Y2 for all subs
clear all
T_0 = read_abcd_beh('~\df_filled_beh_Y0_more.csv');
T_2 =read_abcd_beh('~\df_filled_beh_Y2_more.csv');


load('~/with_2b_2024.mat')
s_table = readtable("~/df_filled_demog_withcog_Y0_more.csv");
sub_11868 = table(s_table.subid_x);
usable_subs0 = innerjoin(sub_11868(with_2b_2024,:),T_0,"LeftKeys","Var1","RightKeys","subids");
tfu = table(T_2.subids, T_2.NBK,  T_2.NIH5,  T_2.smri_thick_cdk_mean,'VariableNames',{'subids','NBK_y2' ,'NIH_y2' ,'thick_y2'});
usable_subs = innerjoin(usable_subs0,tfu,"LeftKeys","Var1","RightKeys","subids");

[~ ,p ,~,sts] = ttest( usable_subs.mat_score, usable_subs.AFC_y2);sts.tstat
[~ ,p ,~,sts] = ttest(nanmean([usable_subs.NBK usable_subs.NIH5./120],2), nanmean([usable_subs.NBK_y2 usable_subs.NIH_y2./120],2));sts.tstat
[~ ,p ,~,sts] = ttest(usable_subs.smri_thick_cdk_mean , usable_subs.thick_y2);sts.tstat

addpath(genpath('Z:\MatlabGraphics\distributionPlot'))
dist_stats_adj = [    usable_subs.mat_score,usable_subs.AFC_y2  ...
   nanmean([usable_subs.NBK usable_subs.NIH5./120],2), nanmean([usable_subs.NBK_y2 usable_subs.NIH_y2./120],2),...
   usable_subs.smri_thick_cdk_mean , usable_subs.thick_y2];
titles ={'Cort FC maturation','Cog Task Performance','Cortical GM Thickness'};
xnames ={'Y0','Y2'};
figure;
subplot(1,3,1)

distributionPlot({dist_stats_adj(:,1)},...    
    'color',{[0.90,0.65,0.73]},'xyOri','normal','histOri','right','showMM',0,'xNames',{'Y0','Y2'})

distributionPlot({dist_stats_adj(:,2)},...
    'color',{[0.70,0.75,0.93]},'xyOri','normal','histOri','left','showMM',0,'xNames','Y2')

line([0.5 ,1],[nanmedian(dist_stats_adj(:,1)) ,nanmedian(dist_stats_adj(:,1))],'Color','red');
line([1 ,1.5],[nanmedian(dist_stats_adj(:,2)) ,nanmedian(dist_stats_adj(:,2))],'Color','blue');
ylabel('AFC score'); ylim([-.4,.65])
set(gca,'FontSize',16,'XTickLabelRotation',45,'XTick',[.5,1.5],'XTickLabel',{'Baseline (9-10 y)','Follow-up (11-12 y)'})
title(titles{1});

subplot(1,3,2)
distributionPlot({dist_stats_adj(:,3)},...    
    'color',{[0.90,0.65,0.73]},'xyOri','normal','histOri','right','showMM',0,'xNames','Y0')

distributionPlot({dist_stats_adj(:,4)},...
    'color',{[0.70,0.75,0.93]},'xyOri','normal','histOri','left','showMM',0,'xNames','Y2')
hold on

ylabel('Mean Accuracy');  ylim([.3,1])
set(gca,'FontSize',16,'XTickLabelRotation',45,'XTick',[.5,1.5],'XTickLabel',{'Baseline (9-10 y)','Follow-up (11-12 y)'})
line([0.5 ,1],[nanmedian(dist_stats_adj(:,3)) ,nanmedian(dist_stats_adj(:,3))],'Color','red');
line([1,1.5],[nanmedian(dist_stats_adj(:,4)) ,nanmedian(dist_stats_adj(:,4))],'Color','blue');
title(titles{2});

subplot(1,3,3)
distributionPlot({dist_stats_adj(:,5)},...    
    'color',{[0.90,0.65,0.73]},'xyOri','normal','histOri','right','showMM',0,'xNames','Y0')


distributionPlot({dist_stats_adj(:,6)},...
    'color',{[0.70,0.75,0.93]},'xyOri','normal','histOri','left','showMM',0,'xNames','Y2')

ylabel('Thickness (mm)');  ylim([2,3.1])
set(gca,'FontSize',16,'XTickLabelRotation',45,'XTick',[.5,1.5],'XTickLabel',{'Baseline (9-10 y)','Follow-up (11-12 y)'})
hold on
line([0.5 ,1],[nanmedian(dist_stats_adj(:,5)) ,nanmedian(dist_stats_adj(:,5))],'Color','red');
line([1 ,1.5],[nanmedian(dist_stats_adj(:,6)) ,nanmedian(dist_stats_adj(:,6))],'Color','blue');
title(titles{3});

export_fig -m5 -transparent Figure2.jpg